# You are given two strings s and t.
# String t is generated by random 
# shuffling string s and then add one more 
# letter at a random position.
# Return the letter that was added to t.

# Example 1:
# Input: s = "abcd", t = "abcde"
# Output: "e"
# Explanation: 'e' is the letter that was added.

# Example 2:
# Input: s = "", t = "y"
# Output: "y"

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        l_s = list(s)
        for word in list(t):
            if word in l_s:
                l_s.remove(word)
            else:
                return word